<?xml version="1.0" encoding="utf-8"?><Database Name="HackerNews" Class="DBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=HackerNews;Integrated Security=True" SettingsObjectName="ycombinator.data.Properties.Settings" SettingsPropertyName="HackerNewsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Article" Member="Articles">
    <Type Name="Article">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UploadedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Article_Comment" Member="Comments" ThisKey="Id" OtherKey="ArticleId" Type="Comment" />
      <Association Name="Article_Like" Member="Likes" ThisKey="Id" OtherKey="ArticleId" Type="Like" />
      <Association Name="User_Article" Member="User" ThisKey="UploadedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Comment" Member="Comment1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ArticleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CommentedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Article_Comment" Member="Article" ThisKey="ArticleId" OtherKey="Id" Type="Article" IsForeignKey="true" />
      <Association Name="User_Comment" Member="User" ThisKey="CommentedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Likes" Member="Likes">
    <Type Name="Like">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ArticleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThumbsUp" Type="ThumbsUpEnum" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Article_Like" Member="Article" ThisKey="ArticleId" OtherKey="Id" Type="Article" IsForeignKey="true" />
      <Association Name="User_Like" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Article" Member="Articles" ThisKey="Id" OtherKey="UploadedBy" Type="Article" />
      <Association Name="User_Comment" Member="Comments" ThisKey="Id" OtherKey="CommentedBy" Type="Comment" />
      <Association Name="User_Like" Member="Likes" ThisKey="Id" OtherKey="UserId" Type="Like" />
    </Type>
  </Table>
</Database>